In [92]:
import numpy as np
from linear_regression import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

In [94]:
# We are looking for 2x + 1
x_train = np.array([[2],
                    [3],
                    [4],
                    [5]])
y_train = np.array([[5],
                    [7],
                    [9],
                    [11]])

In [95]:
lr2 = LinearRegression()
lr2.fit(x_train, y_train)

In [96]:
x_test = np.array([[6],
                   [7]])
y_test = np.array([[13],
                   [15]])

In [97]:
yhat, mse = lr2.evaluate(x_test, y_test)

In [98]:
yhat = lr2.predict(x_test)

In [99]:
yhat

array([[13.],
       [15.]])

In [100]:
yhat, mse

(array([[13.],
        [15.]]),
 array([[1.57772181e-28]]))

In [101]:
lr2.print_vars()

W: [[2.]]
b: [1.]
yhat: [[13.]
 [15.]]
MSE: [[1.57772181e-28]]


In [102]:
lr = LinearRegression()

In [103]:
X, y = fetch_california_housing(data_home='data/', download_if_missing=True, return_X_y = True)

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [105]:
len(X_train), len(X_test), len(y_train), len(y_test)

(14448, 6192, 14448, 6192)

In [106]:
lr.fit(X_train, y_train)

In [107]:
yhat = lr.predict(X_test)
yhat

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [108]:
yhat, mse = lr.evaluate(X_test, y_test)
np.sqrt(mse)

0.7284008391517945

In [109]:
rmses = []
for i in range(20):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42+i)
    lr.fit(X_train, y_train)
    yhat, mse = lr.evaluate(X_test, y_test)
    rmses.append(np.sqrt(mse))   

In [110]:
import pandas as pd
msedf = pd.DataFrame(rmses, columns = ["RMSE"])

In [111]:
print(f'Mean value: {msedf.mean()}\nStandard deviation: {msedf.std()}')

Mean value: RMSE    0.727997
dtype: float64
Standard deviation: RMSE    0.00974
dtype: float64


In [112]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)
yhat_sklearn = reg.predict(X_test)

In [115]:
lr = LinearRegression()
lr.fit(X, y)
yhat = lr.predict(X_test)

In [ ]:
yhat

array([1.46060896, 1.67035792, 2.13574529, ..., 1.64550935, 1.58514273,
       4.93122697])

In [ ]:
yhat_sklearn

array([1.46060896, 1.67035792, 2.13574529, ..., 1.64550935, 1.58514273,
       4.93122697])

In [118]:
yhatdf = pd.DataFrame((yhat, yhat_sklearn))

In [119]:
yhatdf

0         1         2         3         4         5         6     \
0  1.460609  1.670358  2.135745  2.433101  2.328407  2.168262  2.505055   
1  1.460609  1.670358  2.135745  2.433101  2.328407  2.168262  2.505055   

       7         8         9     ...      6182     6183      6184      6185  \
0  2.877709  3.024739  1.763524  ...  1.797564  2.21009  5.602163  1.081977   
1  2.877709  3.024739  1.763524  ...  1.797564  2.21009  5.602163  1.081977   

       6186      6187      6188      6189      6190      6191  
0  2.972898  1.846045  1.016196  1.645509  1.585143  4.931227  
1  2.972898  1.846045  1.016196  1.645509  1.585143  4.931227  

[2 rows x 6192 columns]